customhost = "employee.ctma3tcwwlju.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "jacksiowwoonyew-employee"
customregion = "us-east-1"
